/************************* 시퀀스 *************************/
DROP SEQUENCE  LEFT_USER_SEQ ;
DROP SEQUENCE CLASS_SEQ ;
DROP SEQUENCE CENTER_SEQ ;
DROP SEQUENCE ACCESS_HISTORY_SEQ ;
DROP SEQUENCE  USER_SEQ ;


/************************* 테이블 *************************/
DROP TABLE LEFT_USER_T;
DROP TABLE ACCESS_HISTORY_T;
DROP TABLE CLASSES;

DROP TABLE USER_T;
